FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# MessHallAPI

The MessHallAPI is a simple API for managing users, sessions and attendance.

# Group Users

## Users Collection [/users]

### List All Users [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "John Doe",
                "email": "john@example.com",
                "role": "user"
            },
            {
                "id": 2,
                "name": "Jane Doe",
                "email": "jane@example.com",
                "role": "user"
            }
        ]

### Create a New User [POST]

+ Request (application/json)

        {
            "name": "John Doe",
            "email": "john@example.com",
            "role": "user"
        }

+ Response 201 (application/json)

    + Headers

            Location: /api/users/{id}

    + Body

            {
                "id": 1,
                "name": "John Doe",
                "email": "john@example.com",
                "role": "user"
            }

## Users [/users/{id}]

### List a Single User [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "John Doe",
            "email": "john@example.com",
            "role": "user"
        }

### Delete a User [DELETE]

+ Request (application/json)

        {
            "id": {id}
        }

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "John Doe",
            "email": "john@example.com",
            "role": "user"
        }