export default {
  admin: [
    'user:create',
    'user:update',
    'user:delete',
    'user:view',
    'user:view:all',
    'token:create',
    'token:delete',
    'token:view',
    'token:view:all',
    'user:view:self',
    'token:create:self',
    'token:update:self',
    'token:delete:self',
    'token:view:self',
    'reward:view',
    'reward:view:all',
    'reward:create',
    'reward:delete',
    'reward:update',
  ],
  manager: [
    'user:view:self',
    'token:create:self',
    'token:update:self',
    'token:delete:self',
    'token:view:self',
    'reward:view',
    'reward:view:all',
    'reward:create',
    'reward:delete',
    'reward:update',
  ],
  user: [
    'user:view:self',
    'token:create:self',
    'token:update:self',
    'token:delete:self',
    'token:view:self',
    'reward:view',
    'reward:view:all',
  ],
};
